### PR TITLE
Make DBIx::LogAny great again :)

### PR DESCRIPTION
**Pull request by rehsack**
Extract Statement from $sth ...

### CODE REVIEW

**Review by mjegh — COMMENTED** [review]
Thanks Jens. I obviously don't want to include $dsn ||= "dbi:DBM' and I think I prefer:

    $args[0] = $args[0]->{Statement}
        if blessed($args[0]) &&
            (blessed($args[0]) eq 'DBIx::LogAny::st') &&
                defined ($args[0]->{Statement});
to make sure it is a statement handle.

Also you've put the final drop table after the disconnect.

**Comment by rehsack** [comment]
Before no test is executed, testing with DBD::DBM is better than nothing. Why drop that?

Shall I switch the drop and the disconnect and push again?

**Comment by mjegh** [comment]
Re DBD::DBM I guess that is ok. I forgot it was standard if you have DBI.
Could you switch the drop and change the test as I commented and push again or if you are too busy I think I can edit the commit.
Thanks

**Comment by rehsack** [comment]
"git rebase -i " is a very cool thing :D - pushed

**Comment by mjegh** [comment]
Released your changes as 0.05 but then discovered a bug shown by the addition of your test so released 0.06 with a fix.

**Pull request merged**
